### ISSUE TITLE
Use warning instead of error for field validation in new transformation wizard

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#177]
All the fields are lit up with errors when the UI opens - let's move this to the warning icon (yellow exclamation point).  Brian mentioned that we have to make sure that Finish/Next stay disabled until all required information is provided.

**Comment by bfitzpat** [comment]
May have found a way to handle this - http://git.eclipse.org/c/platform/eclipse.platform.ui.git/plain/examples/org.eclipse.jface.examples.databinding/src/org/eclipse/jface/examples/databinding/snippets/Snippet036ValidationMessageProvider.java

Investigating today.

**Comment by bfitzpat** [comment]
Got this working...

![wizard-kinder-warnings2](https://cloud.githubusercontent.com/assets/530878/7050994/471f31b2-dde2-11e4-93bb-f8a5860fd594.png)

I can:

1) Change the icon in the page header so it's an Information icon or something else.
2) Change any "error" icons to show up as "required" asterisks.

I also:
* Changed the warning to an "info" for "A transformation file with that name already exists."
* Figured out it was a layout problem (GridLayout setting) causing the decorators to be hidden. So that's fixed.

So - is this what you were looking for Keith?

**Comment by bfitzpat** [comment]
Pushed up my branch, but happy to adjust - https://github.com/bfitzpat/fuseide/tree/issue177

**Comment by kcbabo** [comment]
Looks good!  I think we need to change the case where an existing transformation file exists back to a warning though.

**Comment by bfitzpat** [comment]
Can do. Thanks Keith!

**Comment by bfitzpat** [comment]
Done. Thanks! 

https://github.com/fusesource/fuseide/pull/205 is out there for your merging pleasure...

**Comment by kcbabo** [comment]
pushed
