### ISSUE TITLE
Data Transformation: Multiple transformations to one target

### ISSUE THREAD

**Issue by tsedmik** [fusesource/fuseide#237]
I can create more than one transformation with the same target. IMHO it is a bug - one target can be part of only one transformation.

**Comment by kcbabo** [comment]
I don't think we want to prevent this, but a warning or visual cue of some sort would definitely be useful.  The reason I say we don't want to prevent it is there are certain situations where a user might have multiple mappings to the same target field.  One example would be when there are multiple candidate source fields and you want to use one if it's not null, but if it is null you have a "backup" mapping which will write an alternate value.

My instinct is to continue to allow this for now and look to add a visual cue to notify the user that there are multiple mappings to a target field.

**Comment by jpav** [comment]
I understand the concern about multiple source fields being involved in mapping to a single target field, but I'm not sure I agree that we'd ever want those in separate mappings.  Once we support functions like "if", then it seems like the expectation would be a single mapping would contain both source fields, one used in the "then" and the other in the "else".  Also, since we don't currently support "if", shouldn't we disable multiple mapping to the same target until it is supported?

**Comment by kcbabo** [comment]
You can implement the example scenario I outlined above using multiple transformation definitions and no if today.  It does require a change to the underlying Dozer config on the mapping element though (map-null = false).  We are basically weighing two cases against each other:
* Case 1 : the user accidentally maps multiple source fields to a target field.
* Case 2 : it's an advanced/edge use case and the user knows what they are doing.

I'm cool with disallowing mapping multiple source fields to a single target field if you want to go that route.

**Comment by jpav** [comment]
K, didn't realize that was possible.  Guess I can't argue too much with not changing anything :-)
