### ISSUE TITLE
Data Transformation: How to use existing transformation

### ISSUE THREAD

**Issue by tsedmik** [fusesource/fuseide#244]
_Example:_
1. In a Fuse project I create a new Fuse Transformation (via _File --> New --> Other --> Fuse Transformation_)
2. Open Camel editor
3. Add _Data Transformation_ component
4. I'm **unable** to link the component with prepared transformation in step 1

I we allow users to create Fuse Transformation via _File --> New --> ..._, we should facilitate mapping of the transformation configuration to Data Transformation component too.

![screenshot from 2015-04-23 18 10 25](https://cloud.githubusercontent.com/assets/5408450/7301981/672cf9d4-e9e6-11e4-8de1-f62844283fac.png)

**Comment by bfitzpat** [comment]
Ok, I'm starting to work on this a bit. The idea of reusing an existing transformation file is definitely an interesting use case. I'm thinking we add a checkbox something like this:
![resuse-xform-file](https://cloud.githubusercontent.com/assets/530878/7734825/5211e4ea-fef6-11e4-9086-153b0e5d320c.png)

But I'm wondering how we want this to work...

1. What does it mean to "reuse" a transformation file? Can we come up with a viable use case here? 2, Can we introspect the file to discern the source and target details so we know what to add as far as data formats to the Camel configuration?
3. Do we allow the user to change the source and target if they want to reuse a transformation?
4. If they can change the source and target, how do we keep them from invalidating the transformation? Or do we simply skip creating the transformation file as the wizard "finishes"?

**Comment by jpav** [comment]
> On May 20, 2015, at 2:49 PM, Brian Fitzpatrick <notifications@github.com> wrote:
> 
> Ok, I'm starting to work on this a bit. The idea of reusing an existing transformation file is definitely an interesting use case. I'm thinking we add a checkbox something like this:But I'm wondering how we want this to work...
> 
> What does it mean to "reuse" a transformation file? Can we come up with a viable use case here? 2, Can we introspect the file to discern the source and target details so we know what to add as far as data formats to the Camel configuration?

Yes, I agree, lots of questions here.  I believe the current assumption is that the source, target, and transformation files are all copied over to the current project before the wizard is started.  In addition, IIRC, the proposed scenario was that the user might have a different type of source than some existing transformation (e.g., changing the type from XML to JSON), but where the structure is so close that the transformations still apply.  IMHO, I didn’t think this is a very likely scenario, and even so, would not be a very usable approach.  

I do see the need to deal with updates to an existing source or target, which would mean we’d have to a) deal with a lot more validation in the editor, accounting for “broken” mappings, and b) provide an Eclipse validation class to add problems to the Problems view and mark transformations as having a problem when broken.

Lastly, I’d offer that maybe an alternative solution would again to handle similar types via the editor, or editors, by allowing the user to copy and paste, or even DnD, existing mappings from one editor to another, giving us an opportunity at the time of the copy to address any inconsistencies between ancestor names, etc.

> Do we allow the user to change the source and target if they want to reuse a transformation?

IIRC, I think this was the proposed use case.

> If they can change the source and target, how do we keep them from invalidating the transformation? Or do we simply skip creating the transformation file as the wizard "finishes”?

If we continue to go down this route, it seems to me like it would be better to change the checkbox to something like “Copy from existing transformation”, followed by another field and browser button that are only enabled if the checkbox is selected.  Then maybe we have similar fields for the source and target?

**Comment by kcbabo** [comment]
The use case here can be very simple.  I have an existing route definition in my application that pulls data from a directory and sends it to another directory.  I want to add transformation between in between, so I create a new transformation endpoint and configure the mappings using the editor.  In this *same application*, I also have a requirement to receive the same type of data from a JMS queue and route that to another JMS queue with the data being transformed in an identical way to the file -> file example.

Before we get into details on how this might be represented in the tooling, are there any questions/doubts on the use case?  I'm not saying this type of thing will happen all the time, but it certainly seems within the realm of reasonable use cases for a user.

**Comment by bfitzpat** [comment]
Use case seems pretty straightforward when presented that way. But I wanted to make sure we were all on the same page. Just so I'm crystal clear...

1) The user has an existing project with a camel file and transformation file that perform the mapping task they want to accomplish for the specific case detailed in the camel route - i.e. pull data from one directory, transform it to another format, and copy the transformed file to a second directory. 

This results in a project file with a valid camel file (including data formats, endpoint definition, and endpoint reference included in the route), generated classes for source and target data, and a Dozer transformation file. 

This is assumed to be our starting point. Essentially the user has created a camel project with their route, then used our transformation wizard to create a transformation from source to target, and then edited the dozer config in the transformation editor to complete their mapping task.

2. The user now wants to, in the same project with the same camel file and dozer configuration file, map from one JMS Queue to another. We assume that the generated source and target data models are exactly the same as the first case and that the mappings are still valid. 

Correct? I'm getting really picky here because I need to know what the user is starting from and what their task is.

Can I then also guess...

3) The user assumes that the transformation file won't change when using the New Transformation Wizard and pointing at their existing dozer config. The rest of the process is the same. 

The only difference is that the transformation.xml file (dozer config) is not overwritten or changed in any way. A new endpoint is created in the camel route along with any appropriate data formats and they can wire up the endpoint reference in the camel editor.

**Comment by kcbabo** [comment]
You are jumping ahead on me. :-)  Before we talk about how this affects the wizard I wanted to lay down several use cases first, because I think there are some subtle differences between them that will impact if/how we support them directly in the tooling.

For example, in the use case I just brought up, I think the user would be best off using the existing endpoint via a ref: (exactly as we do in the first route).  That is one of the reasons, after all, that we store the endpoints separately in the camel configuration - so they can be reused.

Next use case will be if an endpoint doesn't exist already, but the user has copied in a dozer configuration to their project.  Before we go there, I want to make sure John also agrees on the validity of the first use case.

**Comment by bfitzpat** [comment]
Fair enough. :) Let me double down here though and talk about using that existing endpoint.

What guarantees that it will use the same marshaller and unmarshaller for the JMS to JMS case? (I'm showing my ignorance of where the marshaller comes into play, so my apologies.)

**Comment by jpav** [comment]
I can't argue the validity of the use case, but I personally have never heard of a customer with this use case. I've experienced fan-in/fan-out scenarios, and ones that involve similar sources to be merged into a single target, but never one where separate data flows with the exact same data structures but different source types are involved. This could easily just be my lack of exposure to such scenarios, but this just seems an edge case to me. But I also realize this is one of those YMMV situations, so if you're aware of previous needs for this, then clearly it's worth addressing.

**Comment by kcbabo** [comment]
@bfitzpat the data formats would be the same because the data transformation is identical in both cases (e.g. you can receive the same XML as a payload of a JMS message or in a file).

**Comment by kcbabo** [comment]
@jpav fan-in/fan-out is definitely out there and one way to address this use case; users can attach a variety of consumer (fan-in) endpoints to a route which contains the common transformation logic and then route to different provider endpoints (fan-out).

The main point I'm trying to make here is that there will be a time when the user wants to invoke the same transformation in multiple routes, but we have discretion in terms of how far we go in supporting that.   Sort of like this:
* If there's an existing endpoint in the application and everything is identical (data formats and Dozer config), then the user can simply reference the endpoint directly - they don't have to use the new transformation wizard at all.
* If one of the data formats changes for source or target, but the mapping configuration is identical, then the user might want to reuse the mapping config from within the new transformation wizard.  After we discussed this in the meeting, I believe the consensus was that this is an edge case that carries significant risk of things going bad (e.g. generated models don't line up with models in the existing config)
* If the mapping configuration changes, then the user should always use the new transformation wizard.

If we went with the above, then no changes are required now, which I thought is what we agreed on in our last meeting - basically to wait to see how common this requirement becomes and get some concrete examples from users.

**Comment by jpav** [comment]
I'm in agreement with all of that.

**Comment by bfitzpat** [comment]
Ok. I'm on board so far. Essentially we're talking about reusing an existing endpoint in the camel configuration. It becomes more like the New Transformation Test wizard where the user is specifying a camel file and choosing an endpoint from the drop-down (which also includes the transformation file and data format references). Not getting hung up on the "how" yet - just the basic premise of what the user is attempting to do under the covers.

**Comment by kcbabo** [comment]
I think it can be simpler than that - no wizard required.  The user simply drags a new generic endpoint onto the canvas and points to the existing transformation endpoint using a “ref:” URI.  That can be our initial strategy until we have more concrete feedback from users.  One option in the future would possibly allow a user to copy/paste an existing endpoint on the canvas.

~ keith

**Comment by bfitzpat** [comment]
Even better. :) KISS is always a great principle.

**Comment by jpav** [comment]
Migrated to JIRA: https://issues.jboss.org/browse/FUSETOOLS-1430
